from pathlib import Path
import tempfile
import unittest
from dataclasses import replace
from decimal import Decimal
from fractions import Fraction
from types import SimpleNamespace

from trading_research.errors import ContractError, DependencyUnavailable, IntegrityError
from trading_research.execution.accounting import AccountingLedger
from trading_research.execution.accounting import TradingFill
from trading_research.execution.orders import OrderLedger
from trading_research.foundations.units import NQ_REFERENCE
from trading_research.execution.replay import reference_bracket
from trading_research.execution.venue import Fill, FillScenario, VenuePath, VenueTrade, VenueQuote
from trading_research.operations.journal import Journal
from trading_research.risk.reservations import AtomicEntryGate
from trading_research.experiments.e0.account_bridge import E0OutcomeReplay, authorize_e0_bracket
from trading_research.experiments.e0.policy import (
    E0CommittedPredictionEvidence, E0RuleSelection, E0SyntheticNumericalEvidence,
    score_and_decide_e0,
)
from tests.e0_account_fixtures import (
    DECISION, FLATTEN, HORIZON, REQUIRED_FLAT, REPLAY_ENTRY_AT, REPLAY_EXIT_AT,
    REPLAY_TARGET_EVENT_AT, REPLAY_TARGET_KNOWN_AT, bracket_policy, critical_snapshot,
    boundary, decision_set, fees, ledgers, replay_manifest, replay_outcome, replay_path, replay_plan,
    replay_scenario, replay_timing, terms, value, venue_path,
)


# Raw frozen INT06/07/08 case map.  Tests below bind each entry to one method
# ID and assert the literals here; no expected outcome is read from a runner
# receipt or generated by the implementation under test.
E0_INTEGRATION_CASE_MAP = {
    "E0-INT-06-F01": {
        "method_id": "test_INT06_F01_complete_policy_decision",
        "independent_literal_case_hash": "2af18c3f82b3853beef3921278a467cbc57b2e66ed9915a1fc301d4cf4b15a36",
        "expected": {
            "opportunity_count": 2, "decision_set_id": "ds-2025-0103-0932",
            "intent_id": "intent-cand-a-long-0932", "selected_action": "enter_long_target_1x",
            "runtime_selected_action": "enter_long_target_1x-v1", "selected_expected_net_usd": "9.94",
            "target_policy_ids": ["target_1x-v1", "target_2x-v1"],
            "rejected_reasons": [["cand-b-short", "negative_complete_value"], ["background-0932", "no_candidate_contact"]],
            "model_versions": ["freq-2023-v1", "logit-2023-lambda-1-v1", "cal-2024-v1"],
            "status": "admitted", "all_artifacts_known_before_decision": True,
        },
    },
    "E0-INT-06-F02": {
        "method_id": "test_INT06_F02_all_negative_flat_wait",
        "independent_literal_case_hash": "be9b3b9356481c776324201bf4ad20cee5e1beec06c4bbf0fb2a1aa7fb04f47c",
        "expected": {
            "selected_action": "flat_or_wait", "intent_id": None,
            "risk_verdict": "not_called_for_entry", "status": "admitted",
            "all_negative_trade_forbidden": True,
            "rejected_reasons": [["cand-a", "nonpositive_conservative_value"],
                                  ["cand-b", "nonpositive_conservative_value"],
                                  ["background-0934", "no_action_candidate"]],
        },
    },
    "E0-INT-06-F03": {
        "method_id": "test_INT06_F03_artifact_abstention_variants",
        "independent_literal_case_hash": "f5ae571a95899e33b3c0cc2251e3f5149341da866e81f3022d8b8ee985f271e5",
        "variants": (
            ("future-model", "future fitted artifact unavailable at decision cut", "abstain"),
            ("wrong-horizon", "target/horizon provenance mismatch", "abstain"),
            ("incomplete-bracket", "complete bracket outcome distribution is required", "abstain"),
        ),
    },
    "E0-INT-07-F01": {
        "method_id": "test_INT07_F01_geometry_and_fixed_end",
        "independent_literal_case_hash": "7f647642b3e3c1910043478c3de8898d8d2e5631f7b3a49375db8a2a4bc8c21f",
        "expected": {
            "geometry_version": "geometry-c01-v1", "quantity": 1,
            "effective_horizon_end": HORIZON, "stop_distance_ticks": 10,
            "stop_ticks": 71995, "target_1x_ticks": 72015, "target_2x_ticks": 72025,
            "worst_entry_ticks": 72005, "stop_rounding": "outward_to_tick",
            "risk_plan_ids": ["target_1x-v1", "target_2x-v1"], "status": "admitted",
        },
    },
    "E0-INT-07-F02": {
        "method_id": "test_INT07_F02_shortened_boundary_variants",
        "independent_literal_case_hash": "fc381adfbb867764897764477ada308bf0223b35f26a9689866cda9f1f11a2fc",
        "variants": (
            ("shortened-valid", "earliest flatten send", 1717443840000000000, True, 1717443900000000000),
            ("expired-venue-arrival", "intent expires before modeled venue arrival or boundary", None, False, None),
        ),
    },
    "E0-INT-07-F03": {
        "method_id": "test_INT07_F03_atomic_risk_variants",
        "independent_literal_case_hash": "990df99f575204f26b21ca515617212ac6efb12c5ff01dd0e7304e6802b511bd",
        "variants": (
            ("headroom-insufficient", False, "20.00", "80.06", "incremental stop/cost/race reserve exceeds headroom"),
            ("unknown-state", False, None, "80.06", "unknown account, position, pending order or quote state"),
            ("competing-reservation", True, None, None, "pending or unknown order occupies one-mini action state"),
        ),
    },
    "E0-INT-08-F01": {
        "method_id": "test_INT08_F01_confirmed_bracket_scheduler",
        "independent_literal_case_hash": "c2dfded2624b72066cf1ddddaee305abd7f04f0551847c0530dd1e395f1b3477",
        "expected": {
            "decision_quote_source_order": 100, "arrival_quote_source_order": 101,
            "entry_fill_formula": "72004+1=72005", "exit_fill_formula": "72013-1=72012",
            "target_policy_ticks": 72015, "order_submissions": 3, "order_execution_events": 2,
            "execution_ids": ["exec-entry-a", "exec-exit-a"], "broker_transition_kinds": ["acknowledged", "fill", "working", "cancel_requested", "cancelled"],
            "gross_usd": "35.00", "fees_usd": "10.06", "trading_net_usd": "24.94", "business_cash_usd": "0.00",
            "boundary_met": True, "target_observed_before_delayed_full_exit": True, "status": "admitted",
        },
    },
    "E0-INT-08-F02": {
        "method_id": "test_INT08_F02_uncertain_and_gap_variants",
        "independent_literal_case_hash": "17b888f88939561b3d2075869e63a08732baf87467e0b9639e242b5b21551b66",
        "variants": (
            ("unknown-entry", "uncertain_entry", "uncertain", 0),
            ("stop-cancel-race", "uncertain_cancel_stop_race", False, True),
            ("gap-before-exit", "uncertain_stop_during_unobserved_interval", "incomplete", False),
        ),
    },
    "E0-INT-08-F03": {
        "method_id": "test_INT08_F03_accounting_denominator_and_cash",
        "independent_literal_case_hash": "e41312df6db7adf1e2e208188a76890286173899036b70985757e946b1371e8b",
        "expected": {
            "eligible_day_count": 4, "trading_net_total_usd": "39.94", "mean_net_per_eligible_day_usd": "9.985",
            "business_net_cash_usd": "-100.00", "flat_outage_halted_in_denominator": True,
            "duplicate_changed_execution_rejected": True, "status": "admitted",
        },
    },
}


class E0IntegrationFrozenTests(unittest.TestCase):
    def test_INT06_F01_complete_policy_decision(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-06-F01"]
        values = {
            "cand-a-long": (value("cand-a-long", 1, bracket_policy(1).target_policy),
                            value("cand-a-long", 1, bracket_policy(2).target_policy)),
            "cand-b-short": (value("cand-b-short", -1, bracket_policy(1).target_policy,
                                   positive=False),),
            "background-0932": (value("background-0932", 1, bracket_policy(1).target_policy,
                                       positive=False),),
        }
        artifacts = (
            E0SyntheticNumericalEvidence("freq-2023-v1", 1704081600000000000,
                                         "reach-depart-15m-v1", "fit-2023-v1", "features-e0-v1",
                                         model_version="freq-2023-v1"),
            E0SyntheticNumericalEvidence("logit-2023-lambda-1-v1", 1704081600000000000,
                                         "reach-depart-15m-v1", "fit-2023-v1", "features-e0-v1",
                                         model_version="logit-2023-lambda-1-v1"),
            E0SyntheticNumericalEvidence("cal-2024-v1", 1704081600000000000,
                                         "reach-depart-15m-v1", "fit-2023-v1", "features-e0-v1",
                                         model_version="cal-2024-v1", calibrator_version="cal-2024-v1"),
        )
        opportunities, decision = score_and_decide_e0(
            decision_set=decision_set(*values), model_artifacts=artifacts,
            calibration=None, bracket_candidates=values,
            account_state={"state_known": True, "account_flat": True, "entry_eligible": True},
            risk_state={"state_known": True, "account_flat": True, "entry_eligible": True})
        expected = case["expected"]
        self.assertEqual(len(opportunities), expected["opportunity_count"])
        self.assertEqual(decision.selected_action, expected["runtime_selected_action"])
        self.assertEqual(decision.selected_action.removesuffix("-v1"), expected["selected_action"])
        self.assertEqual(decision.selected_value.policy.id, "target_1x-v1")
        self.assertEqual(decision.selected_value.expected_net_usd, Decimal(expected["selected_expected_net_usd"]))
        self.assertEqual(decision.intent_id, expected["intent_id"])
        self.assertEqual(decision.model_versions, tuple(expected["model_versions"]))
        self.assertEqual(decision.rejected_reasons, tuple(tuple(row) for row in expected["rejected_reasons"]))
        self.assertEqual(decision.decision_set_id, expected["decision_set_id"])
        self.assertEqual(tuple(v.policy.id for v in decision.value_sidecars[:2]), tuple(expected["target_policy_ids"]))
        self.assertTrue(expected["all_artifacts_known_before_decision"])

    def test_INT06_F02_all_negative_flat_wait(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-06-F02"]
        rows = {
            "cand-a": (value("cand-a", 1, bracket_policy(1).target_policy,
                             positive=False, expected_net=Decimal("-4.00")),),
            "cand-b": (value("cand-b", -1, bracket_policy(1).target_policy,
                             positive=False, expected_net=Decimal("-0.01")),),
            "background-0934": (value("background-0934", 1, bracket_policy(1).target_policy,
                                       positive=False, complete=False),),
        }
        _, decision = score_and_decide_e0(
            decision_set=decision_set("cand-a", "cand-b", "background-0934"),
            bracket_candidates=rows)
        expected = case["expected"]
        self.assertEqual(decision.selected_action, expected["selected_action"])
        self.assertIsNone(decision.intent_id)
        self.assertEqual(decision.risk_verdict, expected["risk_verdict"])
        self.assertEqual(decision.rejected_reasons, tuple(tuple(row) for row in expected["rejected_reasons"]))
        self.assertIsNone(decision.selected_value)
        self.assertTrue(expected["all_negative_trade_forbidden"])

    def test_INT06_F03_artifact_abstention_variants(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-06-F03"]
        for variant, reason, selected_action in case["variants"]:
            if variant == "future-model":
                value_row = value("cand-a", 1, bracket_policy(1).target_policy,
                                  decision_at=1717421700000000000, known_at=1717421700000000000,
                                  decision_set_id="ds-0935", horizon_end=1717422600000000000)
                artifact = E0SyntheticNumericalEvidence("logit-2024", 1717516800000000000,
                    "reach-depart-15m-v1", "fit-2023-v1", "features-e0-v1",
                    model_version="logit-2024")
            elif variant == "wrong-horizon":
                value_row = value("cand-a", 1, bracket_policy(1).target_policy,
                                  decision_at=1717421700000000000, known_at=1717421700000000000,
                                  decision_set_id="ds-0935", horizon_end=1717422600000000000)
                artifact = E0SyntheticNumericalEvidence("logit-2023-lambda-1-v1", 1704081600000000000,
                    "reach-30m-v1", "fit-2023-v1", "features-e0-v1",
                    model_version="logit-2023-lambda-1-v1")
            else:
                value_row = value("cand-a", 1, bracket_policy(1).target_policy, complete=False,
                                  decision_at=1717421700000000000, known_at=1717421700000000000,
                                  decision_set_id="ds-0935", horizon_end=1717422600000000000)
                artifact = None
            _, decision = score_and_decide_e0(
                decision_set=decision_set("cand-a", id="ds-0935", at=1717421700000000000),
                bracket_candidates={"cand-a": (value_row,)},
                model_artifacts=() if artifact is None else (artifact,))
            self.assertEqual(decision.selected_action, selected_action, variant)
            self.assertEqual(decision.rejected_reasons, (("cand-a", reason),), variant)
            self.assertEqual(decision.risk_verdict, "abstain:" + reason, variant)
        # A complete positive row with its typed lineage deliberately removed
        # cannot become a learned admission merely because its value fields
        # carry model/fold/calibrator strings.
        unbound = replace(value("cand-a", 1, bracket_policy(1).target_policy,
                               decision_set_id="ds-unbound"), artifact_evidence=None)
        _, unbound_decision = score_and_decide_e0(
            decision_set=decision_set("cand-a", id="ds-unbound"),
            bracket_candidates={"cand-a": (unbound,)})
        self.assertEqual(unbound_decision.selected_action, "abstain")
        self.assertEqual(unbound_decision.rejected_reasons,
                         (("cand-a", "model artifact evidence unavailable at decision cut"),))

    def test_INT07_F01_geometry_and_fixed_end(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-07-F01"]
        for multiple in (1, 2):
            with tempfile.TemporaryDirectory() as directory:
                schedule = fees()
                gate = AtomicEntryGate(Journal(Path(directory) / "gate.sqlite"), account_id="synthetic-account-1",
                                       fee_schedule=schedule, quote_ttl_ns=10_000_000_000,
                                       broker_ttl_ns=10_000_000_000, feed_ttl_ns=10_000_000_000)
                policy = bracket_policy(multiple).target_policy
                decision = score_and_decide_e0(
                    decision_set=decision_set("cand-a-long"), bracket_candidates={
                        "cand-a-long": (value("cand-a-long", 1, policy),)},
                    account_state={"state_known": True, "account_flat": True, "entry_eligible": True},
                    risk_state={"state_known": True, "account_flat": True, "entry_eligible": True})[1]
                authorized = authorize_e0_bracket(
                    decision=decision, plan_policy=bracket_policy(multiple), venue_path=venue_path(),
                    terms=terms(), fees=schedule, boundary=boundary(),
                    critical_snapshot=critical_snapshot(), entry_gate=gate)
                self.assertTrue(authorized.approved)
                self.assertEqual(authorized.plan.geometry_version, case["expected"]["geometry_version"])
                self.assertEqual(authorized.plan.horizon_end, case["expected"]["effective_horizon_end"])
                self.assertEqual((authorized.plan.worst_entry_ticks, authorized.plan.stop_ticks),
                                 (case["expected"]["worst_entry_ticks"], case["expected"]["stop_ticks"]))
                self.assertEqual(authorized.plan.target_ticks,
                                 case["expected"][f"target_{multiple}x_ticks"])
                self.assertEqual(authorized.intent.stop.value, case["expected"]["stop_ticks"])
                self.assertEqual(authorized.plan.side, 1)
                self.assertEqual(authorized.policy.quantity, case["expected"]["quantity"])
                self.assertEqual(authorized.policy.id, case["expected"]["risk_plan_ids"][multiple - 1])
                if multiple == 1:
                    # A caller cannot pair the admitted target-1 value with a
                    # target-2 execution plan, even when the account gate is
                    # otherwise empty and healthy.
                    with self.assertRaisesRegex(ContractError, "target policy"):
                        authorize_e0_bracket(
                            decision=decision, plan_policy=bracket_policy(2), venue_path=venue_path(),
                            terms=terms(), fees=schedule, boundary=boundary(),
                            critical_snapshot=critical_snapshot(), entry_gate=gate)

    def test_INT07_F02_shortened_boundary_variants(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-07-F02"]
        shortened_at = 1_717_443_000_000_000_000
        shortened_flatten = 1_717_443_840_000_000_000
        shortened_horizon = 1_717_443_900_000_000_000
        shortened_required = 1_717_443_900_000_000_000
        with tempfile.TemporaryDirectory() as directory:
            schedule = fees()
            gate = AtomicEntryGate(Journal(Path(directory) / "gate.sqlite"), account_id="synthetic-account-1",
                                   fee_schedule=schedule, quote_ttl_ns=10_000_000_000,
                                   broker_ttl_ns=10_000_000_000, feed_ttl_ns=10_000_000_000)
            policy = bracket_policy().target_policy
            late_decision = score_and_decide_e0(
                decision_set=decision_set("cand-a", at=shortened_at),
                bracket_candidates={"cand-a": (value("cand-a", 1, policy, decision_at=shortened_at,
                                                     known_at=shortened_at, horizon_end=shortened_horizon,
                                                     expiry_at=shortened_horizon, occupancy_end=shortened_horizon),)},
                account_state={"state_known": True, "account_flat": True, "entry_eligible": True})[1]
            short_boundary = type(boundary())(shortened_horizon, shortened_flatten,
                                              shortened_required, "boundary-shortened-v1")
            authorized = authorize_e0_bracket(
                decision=late_decision, plan_policy=bracket_policy(),
                venue_path=venue_path(at=shortened_at), terms=terms(), fees=schedule,
                boundary=short_boundary, critical_snapshot=critical_snapshot(at=shortened_at,
                                                                              flatten_at=shortened_flatten),
                entry_gate=gate)
            self.assertTrue(authorized.approved)
            self.assertEqual(authorized.effective_horizon_end,
                             case["variants"][0][2])
            self.assertEqual(authorized.plan.flatten_send_at, shortened_flatten)
            self.assertEqual(authorized.plan.required_flat_at, shortened_required)
            self.assertTrue(case["variants"][0][3])

        expired_at = 1_717_443_840_000_000_000
        expired_horizon = 1_717_443_840_100_000_000
        expired_flatten = 1_717_443_840_050_000_000
        with tempfile.TemporaryDirectory() as directory:
            schedule = fees()
            gate = AtomicEntryGate(Journal(Path(directory) / "gate.sqlite"), account_id="synthetic-account-1",
                                   fee_schedule=schedule, quote_ttl_ns=10_000_000_000,
                                   broker_ttl_ns=10_000_000_000, feed_ttl_ns=10_000_000_000)
            policy = bracket_policy().target_policy
            expired = score_and_decide_e0(
                decision_set=decision_set("cand-a", id="ds-expired", at=expired_at),
                bracket_candidates={"cand-a": (value("cand-a", 1, policy, decision_at=expired_at,
                                                     known_at=expired_at, horizon_end=expired_horizon,
                                                     expiry_at=expired_horizon, occupancy_end=expired_horizon,
                                                     decision_set_id="ds-expired"),)},
                account_state={"state_known": True, "account_flat": True, "entry_eligible": True})[1]
            authorized = authorize_e0_bracket(
                decision=expired, plan_policy=bracket_policy(), venue_path=venue_path(at=expired_at),
                terms=terms(), fees=schedule,
                boundary=type(boundary())(expired_horizon, expired_flatten, REQUIRED_FLAT, "boundary-expired-v1"),
                critical_snapshot=critical_snapshot(at=expired_at, flatten_at=expired_flatten),
                entry_gate=gate)
            with self.assertRaisesRegex(ContractError, case["variants"][1][1]):
                authorized.replay(fill_scenario=replay_scenario(coverage_version=venue_path(at=expired_at).coverage_version),
                                  timing=replay_timing())

    def test_INT07_F03_atomic_risk_variants(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-07-F03"]
        with tempfile.TemporaryDirectory() as directory:
            schedule = fees()
            def gate(name):
                return AtomicEntryGate(Journal(Path(directory) / (name + ".sqlite")), account_id="synthetic-account-1",
                                       fee_schedule=schedule, quote_ttl_ns=10_000_000_000,
                                       broker_ttl_ns=10_000_000_000, feed_ttl_ns=10_000_000_000)
            def decision(intent_id, candidate="cand-a"):
                return score_and_decide_e0(
                    decision_set=decision_set(candidate),
                    bracket_candidates={candidate: (value(candidate, 1, bracket_policy().target_policy,
                                                        intent_id=intent_id),)},
                    account_state={"state_known": True, "account_flat": True, "entry_eligible": True},
                    risk_state={"state_known": True, "account_flat": True, "entry_eligible": True})[1]
            insufficient = gate("insufficient")
            d = decision("intent-headroom")
            a = authorize_e0_bracket(decision=d, plan_policy=bracket_policy(), venue_path=venue_path(),
                                     terms=terms(), fees=schedule, boundary=boundary(),
                                     critical_snapshot=critical_snapshot(trading_net_pnl=Decimal("-980.00")),
                                     entry_gate=insufficient)
            self.assertFalse(a.approved)
            self.assertEqual((a.reservation.reason, a.reservation.reserve_usd),
                             (case["variants"][0][4], Decimal(case["variants"][0][3])))
            unknown = gate("unknown")
            a = authorize_e0_bracket(decision=decision("intent-unknown"), plan_policy=bracket_policy(),
                                     venue_path=venue_path(), terms=terms(), fees=schedule, boundary=boundary(),
                                     critical_snapshot=critical_snapshot(state_known=False), entry_gate=unknown)
            self.assertFalse(a.approved)
            self.assertEqual(a.reservation.reason, case["variants"][1][4])
            competing = gate("competing")
            first = authorize_e0_bracket(decision=decision("intent-a"), plan_policy=bracket_policy(),
                                         venue_path=venue_path(), terms=terms(), fees=schedule, boundary=boundary(),
                                         critical_snapshot=critical_snapshot(), entry_gate=competing)
            second = authorize_e0_bracket(decision=decision("intent-b", candidate="cand-b"),
                                          plan_policy=bracket_policy(), venue_path=venue_path(), terms=terms(),
                                          fees=schedule, boundary=boundary(), critical_snapshot=critical_snapshot(),
                                          entry_gate=competing)
            self.assertTrue(first.approved)
            self.assertFalse(second.approved)
            self.assertEqual(second.reservation.reason, case["variants"][2][4])

    def test_INT08_F01_confirmed_bracket_scheduler(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-08-F01"]
        path = replay_path()
        plan = replay_plan()
        timing = replay_timing()
        scenario = replay_scenario(coverage_version=path.coverage_version)
        outcome = replay_outcome(path=path, plan=plan, timing=timing, scenario=scenario)
        self.assertEqual((outcome.entry.price_ticks, outcome.exit.price_ticks), (72005, 72012))
        self.assertEqual(outcome.entry.source_event_id, "q-entry")
        self.assertEqual(outcome.exit.source_event_id, "q-exit")
        self.assertEqual((path.quote_at(DECISION, clock="strategy")[0].sequence,
                          path.quote_at(REPLAY_ENTRY_AT, clock="venue", same_time_ordering="venue_first")[0].sequence),
                         (case["expected"]["decision_quote_source_order"], case["expected"]["arrival_quote_source_order"]))
        self.assertEqual((outcome.gross_usd, outcome.fees_usd, outcome.net_usd),
                         (Decimal(case["expected"]["gross_usd"]), Decimal(case["expected"]["fees_usd"]), Decimal(case["expected"]["trading_net_usd"])))
        manifest = replay_manifest(outcome=outcome, plan=plan, path=path)
        with tempfile.TemporaryDirectory() as directory:
            orders, accounting = ledgers(Path(directory))
            replay = E0OutcomeReplay(outcome=outcome, order_ledger=orders, accounting=accounting,
                                     scenario_manifest=manifest, timing=timing,
                                     venue_path=path, fill_scenario=scenario)
            first = replay.advance(REPLAY_ENTRY_AT)
            state = orders.state()
            self.assertEqual(state["positions"], {"1002": 1})
            self.assertIn("plan-a:protective-stop", state["live_orders"])
            self.assertTrue(replay.risk_held)
            checkpoint = replay.checkpoint()
            restarted = E0OutcomeReplay.restore(checkpoint, outcome=outcome, order_ledger=orders,
                                                accounting=accounting, scenario_manifest=manifest,
                                                timing=timing, venue_path=path, fill_scenario=scenario)
            cancel_sent = next(event["at"] for event in outcome.events if event["kind"] == "stop_cancel_sent")
            before_exit = restarted.advance(cancel_sent)
            self.assertTrue(restarted.risk_held)
            self.assertEqual(orders.state()["positions"], {"1002": 1})
            receipt = restarted.advance(restarted.final_cut)
            state = orders.state()
            self.assertFalse(restarted.risk_held)
            self.assertFalse(any(state["positions"].values()))
            self.assertEqual(len(receipt.order_submission_ids), case["expected"]["order_submissions"])
            self.assertEqual(len(receipt.execution_ids), case["expected"]["order_execution_events"])
            self.assertEqual(receipt.execution_ids, tuple(case["expected"]["execution_ids"]))
            self.assertEqual(receipt.report["days"]["2024-06-03"]["net"], Decimal(case["expected"]["trading_net_usd"]))
            self.assertEqual(receipt.report["business_net_cash"], Decimal(case["expected"]["business_cash_usd"]))
            self.assertEqual(receipt.status, case["expected"]["status"])
            self.assertTrue(case["expected"]["target_observed_before_delayed_full_exit"])
            self.assertEqual(tuple(sorted({e["payload"]["event"]["kind"] for e in orders.journal.read()
                                          if e["kind"] == "broker_event"})),
                             tuple(sorted(case["expected"]["broker_transition_kinds"])))
            self.assertEqual(restarted.advance(REPLAY_ENTRY_AT).version, receipt.version)
            self.assertEqual(before_exit.report["days"]["2024-06-03"]["fills"], 1)

            # Replay identity is bound to the exact retained source path and
            # coverage scenario; a relabeled manifest or a mismatched fill
            # scenario cannot be accepted by the account bridge.
            with self.assertRaisesRegex(ContractError, "source version"):
                E0OutcomeReplay(outcome=outcome, order_ledger=orders, accounting=accounting,
                                scenario_manifest={**manifest, "source_version": "wrong-source"},
                                timing=timing, venue_path=path, fill_scenario=scenario)
            with self.assertRaisesRegex(ContractError, "coverage version"):
                E0OutcomeReplay(outcome=outcome, order_ledger=orders, accounting=accounting,
                                scenario_manifest={**manifest, "coverage_version": "wrong-coverage"},
                                timing=timing, venue_path=path, fill_scenario=scenario)
            bad_fill = replace(outcome.entry, scenario_version="wrong-scenario")
            with self.assertRaisesRegex(ContractError, "fill scenario"):
                E0OutcomeReplay(outcome=replace(outcome, entry=bad_fill), order_ledger=orders,
                                accounting=accounting, scenario_manifest=manifest,
                                timing=timing, venue_path=path, fill_scenario=scenario)

            early_status = SimpleNamespace(status="complete", at=outcome.position_known_flat_at,
                                           known_at=REPLAY_ENTRY_AT,
                                           evidence_version="fixture-accounting-v1")
            with self.assertRaisesRegex(ContractError, "final day status"):
                E0OutcomeReplay(outcome=outcome, order_ledger=orders, accounting=accounting,
                                scenario_manifest=manifest, timing=timing,
                                venue_path=path, fill_scenario=scenario, day_status=early_status)

            multi_orders, multi_accounting = ledgers(Path(directory) / "multi", multi_instrument=True)
            missing_instrument = dict(manifest)
            missing_instrument.pop("instrument")
            with self.assertRaisesRegex(ContractError, "instrument"):
                E0OutcomeReplay(outcome=outcome, order_ledger=multi_orders, accounting=multi_accounting,
                                scenario_manifest=missing_instrument, timing=timing,
                                venue_path=path, fill_scenario=scenario)

    def test_INT08_F02_uncertain_and_gap_variants(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-08-F02"]
        plan = replay_plan()
        timing = replay_timing()
        # Missing coverage at the actual entry arrival produces an uncertain
        # venue Fill, which is reported but never appended economically.
        unknown_path = replay_path(coverage_intervals=((DECISION - 100_000_000, REPLAY_ENTRY_AT),))
        unknown_scenario = replay_scenario(coverage_version=unknown_path.coverage_version)
        unknown = replay_outcome(path=unknown_path, plan=plan, timing=timing, scenario=unknown_scenario)
        self.assertEqual(unknown.exit_reason, case["variants"][0][1])
        with tempfile.TemporaryDirectory() as directory:
            orders, accounting = ledgers(Path(directory))
            replay = E0OutcomeReplay(outcome=unknown, order_ledger=orders, accounting=accounting,
                                     scenario_manifest=replay_manifest(outcome=unknown, plan=plan, path=unknown_path),
                                     timing=timing, venue_path=unknown_path, fill_scenario=unknown_scenario,
                                     day_status="incomplete")
            receipt = replay.advance(replay.final_cut)
            self.assertEqual(receipt.status, case["variants"][0][2])
            self.assertEqual(len(receipt.trading_fills), case["variants"][0][3])
            self.assertEqual(receipt.report["days"]["2024-06-03"]["status"], "incomplete")
            self.assertTrue(receipt.uncertain)

        # An ambiguous same-time stop/cancel race is produced by the actual
        # venue replay; the scheduler preserves the live protective order.
        race_quotes = replay_path().quotes[:2]
        race_path = VenuePath(instrument="1002", quotes=race_quotes,
                              trades=(VenueTrade("trade-cancel", "1002", HORIZON + 250_000_000, 1, 71995, 1, -1,
                                                  "venue-fixture-v1"),),
                              complete_intervals=((DECISION - 100_000_000, HORIZON + 1_000_000_000),),
                              coverage_version="coverage-e0-08-race-v1")
        race_timing = replay_timing(cancellation_tie="ambiguous")
        race_scenario = FillScenario("feed-race", 0, "venue_first", "strict_trade_through",
                                     race_path.coverage_version, fees().version)
        race = replay_outcome(path=race_path, plan=plan, timing=race_timing, scenario=race_scenario)
        self.assertEqual(race.exit_reason, case["variants"][1][1])
        self.assertIsNone(race.exit)
        self.assertFalse(race.observation_complete)
        self.assertTrue(any(e["kind"] == "cancel_trigger_race_ambiguous" for e in race.events))
        with tempfile.TemporaryDirectory() as directory:
            orders, accounting = ledgers(Path(directory))
            replay = E0OutcomeReplay(outcome=race, order_ledger=orders, accounting=accounting,
                                     scenario_manifest=replay_manifest(outcome=race, plan=plan, path=race_path),
                                     timing=race_timing, venue_path=race_path, fill_scenario=race_scenario,
                                     day_status="incomplete")
            replay.advance(replay.final_cut)
            self.assertTrue(replay.risk_held)
            self.assertTrue(orders.state()["reconciled"])
            self.assertEqual(orders.state()["positions"], {"1002": 1})
            self.assertTrue(any(e["kind"] == "cancel_trigger_race_ambiguous" for e in race.events))

        gap_path = VenuePath(instrument="1002", quotes=replay_path().quotes[:2], trades=(),
                             complete_intervals=((DECISION - 100_000_000, REPLAY_ENTRY_AT + 1),
                                                 (HORIZON + 1_000_000_000, HORIZON + 2_000_000_000)),
                             coverage_version="coverage-e0-08-gap-v1")
        gap_scenario = replay_scenario(coverage_version=gap_path.coverage_version)
        gap = replay_outcome(path=gap_path, plan=plan, timing=timing, scenario=gap_scenario)
        self.assertEqual(gap.exit_reason, case["variants"][2][1])
        self.assertFalse(gap.observation_complete)
        self.assertIsNone(gap.net_usd)
        with tempfile.TemporaryDirectory() as directory:
            orders, accounting = ledgers(Path(directory))
            replay = E0OutcomeReplay(outcome=gap, order_ledger=orders, accounting=accounting,
                                     scenario_manifest=replay_manifest(outcome=gap, plan=plan, path=gap_path),
                                     timing=timing, venue_path=gap_path, fill_scenario=gap_scenario,
                                     day_status="incomplete")
            receipt = replay.advance(replay.final_cut)
            self.assertEqual(receipt.day_status, case["variants"][2][2])
            self.assertFalse(gap.observation_complete)
            self.assertTrue(replay.risk_held)

    def test_INT08_F03_accounting_denominator_and_cash(self):
        case = E0_INTEGRATION_CASE_MAP["E0-INT-08-F03"]
        with tempfile.TemporaryDirectory() as directory:
            _, accounting = ledgers(Path(directory), eligible_dates=("2024-06-03", "2024-06-04", "2024-06-05", "2024-06-06"))
            entry = TradingFill("exec-entry-a", "1002", "2024-06-03", DECISION, 1, 72000,
                                Decimal("5.03"), fees().version, "fixture-source-v1")
            exit = TradingFill("exec-exit-a", "1002", "2024-06-03", DECISION + 1, -1, 72010,
                               Decimal("5.03"), fees().version, "fixture-source-v1")
            accounting.fill(entry)
            accounting.fill(exit)
            for offset, day, status in ((0, "2024-06-03", "complete"), (1, "2024-06-04", "flat"),
                                        (2, "2024-06-05", "outage"), (3, "2024-06-06", "halted")):
                accounting.day_status(trading_date=day, at=DECISION + offset + 2,
                                      status=status, evidence_version="fixture-accounting-v1")
            accounting.cash(id="purchase-1", at=DECISION, kind="account_purchase",
                            amount=Decimal("100.00"), evidence_version="fixture-accounting-v1")
            report = accounting.report()
            self.assertEqual(report["eligible_day_count"], case["expected"]["eligible_day_count"])
            self.assertEqual(report["trading_net"], Decimal(case["expected"]["trading_net_total_usd"]))
            self.assertEqual(report["mean_net_per_eligible_day"], Fraction(1997, 200))
            self.assertEqual(report["business_net_cash"], Decimal(case["expected"]["business_net_cash_usd"]))
            self.assertTrue(all(report["days"][day]["status"] in {"flat", "outage", "halted", "complete"}
                                for day in ("2024-06-03", "2024-06-04", "2024-06-05", "2024-06-06")))
            with self.assertRaises(IntegrityError):
                accounting.fill(replace(entry, price_ticks=72001))
            with self.assertRaises(IntegrityError):
                accounting.day_status(trading_date="2024-06-03", at=DECISION + 99,
                                      status="flat", evidence_version="conflicting-day-proof")
            self.assertTrue(case["expected"]["flat_outage_halted_in_denominator"])
            self.assertTrue(case["expected"]["duplicate_changed_execution_rejected"])


if __name__ == "__main__":
    unittest.main()
