from pathlib import Path
import json
base=Path('/workspace/planning/trading-model');p=base/'review/external/skylit'; inv=json.loads((p/'inventory.json').read_text())
summaries={
1:('Access status','Platform overview describes API access as coming soon; the later changelog describes a limited beta. Documentation is not evidence of usable account entitlement.','Unresolved dependency for optional vendor benchmarks; our architecture must run on independently audited acquired data.'),
2:('Support','Support links and channels provide routes for questions, not algorithmic definitions or evidence of edge.','Reference only; no support messages or account actions were sent.'),
3:('Version and access','June 29 changelog describes limited beta API access for approved developers. Interfaces and claims require versioned capture.','Retain versioned provenance and verify entitlement before any future paid integration.'),
4:('Heatmap premise','Gamma/vanna strike boards, large nodes, multi-asset comparison, and changing node magnitude organize discretionary location/context hypotheses. Screenshots do not reveal complete holdings, formulas, fills, or uncertainty.','Retain measurable board states; replace narrative certainty with causal targets and uncertainty-aware node models.'),
5:('Audience','Product is aimed at active traders interpreting options-related market structure.','Reference only; audience claims do not validate economic suitability for one-mini NQ/ES execution.'),
6:('Core concepts','Absolute magnitude and sign interact; large nodes, intervening gatekeepers, clusters, early-session movement versus later pinning, post-touch growth/decay, and migrating ceilings/floors describe candidate states. The page also makes retest-frequency, broker-liquidation-time, OPEX, and margin claims without independently demonstrated estimates. Sparse exposure is not observed order-book liquidity.','Retain node-state hypotheses and mechanically decomposed updates. Reject universal midpoint avoidance or an asserted 1:1 payoff implying no edge. Broker-specific timing remains an unverified event hypothesis; do not identify traders from it.'),
7:('Navigation','Board controls change symbol, metric, expiration, view, and replay context.','Record the exact board universe and settings with every derived observation; display settings cannot define a stable research feature silently.'),
8:('Using boards','The guide prefers agreement among SPX/SPY/QQQ and describes node proximity and multi-board context.','Replace mandatory agreement with an ablated joint predictor: a source-market reaction may matter to NQ without a local QQQ/NQ node.'),
9:('Best practices','Prior movement, remaining room, GEX/VEX structure, source-market floors and stronger nodes elsewhere can alter a local trade interpretation.','Retain competing opportunities, cross-market transmission, and remaining-payoff tests. Do not impose an unsupported payoff-ratio cutoff independent of hit probability and costs.'),
10:('Limitations','News, liquidity conditions, squeezes, expiration effects, and stale or changing maps can defeat a displayed setup.','Use explicit event/freshness/universe states and failure labels; limitations motivate tests rather than discarding options-derived locations.'),
11:('Pitfalls','The guide discusses proximity margins, chasing, and behavioral errors.','Treat instrument-dependent margins as benchmarks to calibrate in volatility/tick units; psychological admonitions map to deterministic risk and re-entry controls, not explanatory alpha.'),
12:('FAQ','Kings, gatekeepers, clusters, and stacked concentrations describe board topology and possible interactions.','Represent topology continuously and retain exceptions; no named pattern is automatically a necessary trade condition.'),
13:('Cases','TSLA, SPX/SPY/QQQ, and NFLX examples illustrate downward paths, cross-board rejection, changing node strength, and a later gap. Event and stock-split context may confound the NFLX story.','Case fixtures preserve visible sequences; screenshots and selected successes are not realized-fill or causal evidence.'),
14:('Resources','External video/channel links are supplied, without all referenced audiovisual contents in the captured pages.','Unreviewed linked videos are explicitly outside the reviewed-text claim; request specific missing proprietary explanation only if a proposed component depends on it.'),
15:('Whipsaw','Opposing larger nodes with limited intervening structure define the illustrated whipsaw configuration.','Retain topology, reach, alternating-touch, and time-to-resolution hypotheses; estimate conditional outcomes on complete opportunity sets.'),
16:('Rainbow road','Many intermingled substantial nodes create an unclear path in the examples.','Compare uncertainty-based abstention with predictive topology models; do not equate visual complexity with proven unprofitability.'),
17:('Gatekeeper','A nearer intervening node may react before a farther target. Suggested scaling is incompatible with the primary one-contract experiment.','Preserve nearer-versus-deeper opportunity cost, stopping-time labels, and single-position exit choices; no partial exits in the primary policy.'),
18:('Distant/speculative nodes','Examples compare large distant nodes, nearer intervening levels, prior rallies, and horizon limitations. Intentional decoy positioning is not observable.','Retain reachability and expiry-conditioned opportunity; discard inferred intent as a ground-truth label.'),
19:('Trend','Trendward node migration, fading opposing structure, and renewed magnitude at departed nodes frame continuation and possible return.','Separate holdings-assumption changes from spot/IV/time repricing and test migration/return forecasts incrementally.'),
20:('Rug setup','The illustrated sequence combines unwinding overhead structure and missing downside support; another board can provide the source catalyst.','Retain directed source-event features, including SPY-to-QQQ/NQ transmission without a local counterpart; test delays and executable incremental payoff.'),
21:('Trading maxims','The page gives categorical reversal and color-based trading instructions.','Benchmark-only rules; reject them as universal eligibility restrictions. Context/Location can independently originate entries.'),
22:('Topping/bottoming','Multi-expiry stair steps, declining higher structures, and changes in lower support are interpreted as topping; renewed higher-node growth can invalidate it.','Retain time-evolving strike-expiry graphs and mirrored hypotheses, with causal invalidation and competing explanations.'),
23:('General help','General product support and orientation.','Reference only.'),
24:('Written guides','Links return to relevant written documentation already included in this review.','Retain navigational coverage; do not count duplicate guides as independent evidence.'),
25:('Videos','Video links and channels are listed; their unseen content is not equivalent to the page text reviewed here.','Record unavailable audiovisual detail; no invented transcripts or omitted-formula reconstruction.'),
26:('Community threads','Links lead to community/private discussion threads not accessed in this task.','Unavailable external evidence; design does not depend on private account access.'),
32:('Flowseeker','Print feed, contract aggregation, ranking, lookup, and bookmarks expose DTE, moneyness, premium, OI, volume/OI, side, sweep, and multi-leg filters. Trade side and print size do not establish intent or new holdings. Off-exchange equity prints are not automatically directional.','Keep print→contract→strike→expiry→chain→sector aggregations in separate units. Log unselected candidates; model side/multi-leg uncertainty; preserve OI reporting delay. Atlas flow-bar height is premium, not contracts.'),
85:('Atlas','Expiration selection changes the board universe. Orb clamping/opacity changes visual size. Replay is described as historical; derived NQ/ES overlays use selected related boards with undocumented mapping. Flow, dark-print, heatmap, and named layouts combine existing data.','Verify as-of behavior; version visual transformations. Extend Nasdaq comparisons explicitly to NDX/NDXP. Treat overlay mapping and beta projections as unreplicated vendor benchmarks, not formulas inferred from screenshots.'),
86:('Drawing presets','Drawing tools support ratios, reversal/log controls, and mutable presets.','Presentation/reference only unless a precise causal rule is separately specified; version presets used to construct benchmark fixtures.'),
87:('GEX VWAP','Each minute, exposure magnitude weights strikes. Upper/lower averages split around the resulting center, not spot. Node filtering is a fraction of king magnitude, not a percentile. Optional early-session envelopes require enough board minutes; session envelopes widen. Missing boards create gaps.','Specify our transparent magnitude-weighted formula and sign-specific alternatives. Preserve opening-window availability, expiry scope, and mapping uncertainty; do not call this traded-volume VWAP.'),
88:('Price VWAP','Bar price times volume supports period resets and weighted-deviation or percentage bands. SPXW borrows ES volume, including futures-session effects on larger bars.','Label index proxy weighting explicitly. Compare trade-level futures VWAP with bar approximations; forming bars remain provisional and resets are not price gaps.'),
89:('CVD','Documentation describes sided-volume accumulation, reset/carry modes, averages, missing-data behavior, and SPXW using ES flow. Minute-based reconstruction can change live intraminute wick appearance.','Minute net volume cannot recover true trade-sequence CVD highs/lows. Preserve user-required trade-level and size-cohort CVD OHLC separately, plus options/gamma variants.'),
90:('Volume profile','Despite histogram language, the described price allocation spreads bar volume across bar range. Defaults and tie/expansion rules affect POC/value area; empty neighbors may stop expansion before the nominal coverage.','Use actual trade-price and signed trade-price profiles for canonical futures objects. Keep the vendor bar allocation as a labeled approximation, and avoid future-viewport selection.'),
91:('TPO','Letters represent chart bars visiting price rows, with configurable/repeating windows and adaptive row sizing. Prior naked levels appear at the next session open; display hides distant levels.','Compare fixed-tick, causally anchored TPO with OHLC visitation approximations. Separate object availability at completed formation from delayed display and censoring by viewport.'),
}
head='''# External research and evidence register\n\nReviewed public documentation captured 2026-09-06 UTC. Claims describe the cited documentation, not independently verified profitability, vendor access, proprietary formulas, or data latency. The complete URL/hash inventory is [Skylit inventory](review/external/skylit/inventory.json); captured sources are immutable review copies. Source-derived summaries are concise; design dispositions are our proposed tests or engineering choices. No paid API, account integration, subscription, or order was initiated.\n\n## Skylit: mechanism-level findings\n\n'''
for n,(name,claim,decision) in summaries.items():
 d=inv['pages'][n-1]; head+=f"### EXT-{n:03d} — {name}\n\nSource: [{d['id']}]({d['url']}), captured 2026-09-06, full readable text L1–{d['readable_lines']}.\n\nEvidence/claim: {claim}\n\nDisposition and improvement: {decision}\n\n"
(base/'EXTERNAL_RESEARCH.md').write_text(head)
print('wrote',len(summaries),'findings')
