from pathlib import Path
import json,hashlib,datetime
r=Path('/workspace/trading-research');plan=Path('/workspace/planning/trading-research');coord=Path('/workspace/coordination/trading-research-cursor');p=r/'reports/auction-flow-runs/541e27aac8fd7ce9a91be85d5c53a3654e7583559caed957fd0ff5ab337500e8';w=json.loads((p/'worker.json').read_text());e=json.loads((p/'execution.json').read_text());cost=w['actual_source_preflight']['source_cost_projection'];now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def ref(p):
 raw=p.read_bytes();return {'path':str(p),'sha256':hashlib.sha256(raw).hexdigest(),'size_bytes':len(raw)}
report=r/'reports/auction-flow-performance23-review.md'
report.write_text(f'''# Auction/flow performance checkpoint 23

Accepted at {e['finished_at']}. [Execution]({p}/execution.json); [worker]({p}/worker.json). This is engineering/source equivalence evidence, not completion of annual family validation, Context or Location.

121 relevant tests, all nine complete retained source-value comparisons against benchmark18 and all three adjacent-window continuation comparisons passed. C++ projection, quote-slice fusion and native quote updates executed on every actual unit. Complete logical quote/measurement values remain equal; original native floating tolerances remain unchanged. Compilation used -O3, no fast math and disabled contraction.

The exact quote replay representation retains original immutable sources plus bounded descriptors. Each completed writer independently replays every original quote column and the entire producer source manifest except timing. That includes raw all-field identity, physical row addresses, source selection and terminal carry. Initial carry remains distinct. Readers pin source implementation/runtime and verify identity again when exhausted. Trade/native Parquet and every source alternative remain retained. Descriptor and required replay CPU are charged; later rereads are not free.

Measured source-only allowance: **{cost['source_pipeline_cpu_allowance']:,.3f} CPU seconds**, down from160,866.336 in18; **{cost['source_storage_allowance_including_failure_reserve']:,.0f} output bytes**, down from419,007,169,666. Both retain the original1.5 margin and separate failure-output reserves. At17 continuously busy workers this CPU allowance is2.494 hours; this is not an observed full-run time or full-project ETA.

A separately frozen, empirically calibrated quote-cost model accounts for both slice overhead and quote rows. It uses the two original quiet units for fixed slice cost and all nine units for residual row cost, with one quote per raw row as the prospective upper population. Its source allowance is134,722.304 CPU seconds (2.201 hours at17busy workers). This is a costing correction, not an additional implementation speedup. It must be tested on the independent17-window holdout before use; V14 records its exact coefficients before that run.

The full correctness benchmark consumed **{e['cpu_seconds']:.6f} CPU seconds / {e['wall_seconds']:.3f} elapsed seconds / {e['attempt_output_bytes']:,} bytes**. It is slightly slower than18 because replay integrity is exercised repeatedly during value and continuation comparisons. Busy-window quote CPU fell roughly15–23%; quiet-window quote CPU rose modestly. Do not describe this benchmark itself as an end-to-end speedup.

The downstream source-reuse path already passed attempt20:70 tests,18 complete anchor/cohort payloads across9source populations unchanged,122.657CPU seconds /130.973elapsed seconds. It authenticates and reuses accepted source/trade artifacts. Profile extrema hoisting and cohort interval indexing remain verified by17/19; the complete anchor/cohort catalogue is not removed.

Attempts21 and22 remain charged:21 stopped on test-harness compatibility failures before source scans (8.134236CPU s,223,680bytes);22 passed120tests but was deliberately stopped after real16-bit flags exposed unnecessary fallback (123.815261CPU s,96,548,410bytes).23 corrects that conversion and requires per-unit compiled execution. No budgets or failures were reset.

The hardware plan now permits17single-thread children plus a4GiB coordinator within72GiB aggregate address space, below the actual17.85core/82,999,996,416-byte allocation. Its tests passed. Actual throughput/utilization is pending the registered17-distinct-file full-UTC-day holdout. Each independent holdout begins with explicitly declared observed-prefix state; it does not infer pre-window coverage or replace production's continuous same-source carry.

Full remaining annual/anchor/causal/cohort statistics, all other validation families, Context fitting and Location studies are uncosted and unfinished. Complete end-to-end under-three-hour feasibility is **not established**. Full production extraction has not started.
''')
p=plan/'START_HERE.md';s=p.read_text();a=s.index('- **Auction/flow source calculations:**');b=s.index('- **Shared infrastructure:**',a);s=s[:a]+'''- **Auction/flow source calculations:** benchmark **23** passed121affected tests, all9complete source comparisons and all3continuation replays. C++ quote/native fusion and exact raw-source quote replay are accepted for this scope. [Performance review](/workspace/trading-research/reports/auction-flow-performance23-review.md).
- **Broader auction/flow checks:** check17 passed338tests and retained complete anchors/cohorts. Downstream20 reused9accepted source populations and reproduced18complete anchor/cohort payloads in130.973elapsed seconds. Full annual family statistics remain unfinished.
'''+s[b:]
a=s.index('The latest conservative source-only projection');b=s.index('\n## What remains',a);s=s[:a]+'''The latest source-only allowance is **152,641.745 CPU-seconds and261.16GB**, retaining all original margins and failure reserves. Removing duplicate quote Parquet resolves the earlier419GB storage projection on the measured basis. A separately frozen dual-count quote-cost model gives134,722.304CPU seconds; it is an empirical costing correction pending independent17-window validation. Neither estimate includes unimplemented downstream/all-family/Context/Location work, and neither establishes the user's under-three-hour end-to-end target. Full extraction has not started.
'''+s[b:]
s=s.replace('Auction/flow has **16 attempts, 4976.148235 CPU-seconds and 3,986,633,029 output bytes**','Auction/flow has **23 attempts, 6646.394269 CPU-seconds and 5,107,552,193 output bytes**');s=s.replace('The registered runner compiles it with GCC13.3','The registered runner compiles it with GCC13.3');p.write_text(s)
p=plan/'STATUS.md';s=p.read_text().replace('after completed auction/flow benchmark16','after completed auction/flow benchmark23').replace('after completed auction/flow benchmark 16','after completed auction/flow benchmark 23');s=s.replace('Latest benchmark16:74affected tests','Latest benchmark23:121affected tests').replace('Latest benchmark 16: 74 affected tests, nine complete source/measurement equivalence comparisons, three full source continuation cuts. Broader check 9: 336 tests, full per-window anchor and hard/soft cohort calculations.','Latest benchmark23:121affected tests, nine complete source/measurement comparisons, three continuation cuts. Check17:338tests and full anchor/cohort checks; downstream20 reproduced18complete payloads in130.973elapsed seconds.');a=s.index('Auction/flow: **16/32');b=s.index('\n## Checkpointed drafts',a);s=s[:a]+'''Auction/flow: **23/32attempts,6,646.394269/192,000CPU-seconds,5,107,552,193retained output bytes** against256GiB. Jumbo remains16/24attempts and1,473.051801/20,000CPU-seconds. Read live ledgers before execution; all failure/deviation records remain retained.

[Accepted performance23review](/workspace/trading-research/reports/auction-flow-performance23-review.md): source-only allowance152,641.745CPU seconds /261.16GB, versus160,866.336CPU seconds /419.01GB in18. The separate dual-count quote estimate134,722.304CPU seconds is a frozen empirical cost recalibration awaiting17-window holdout validation, not an additional algorithmic speedup. The121-test full correctness benchmark took398.110elapsed seconds; downstream20took130.973seconds with all18payloads unchanged. Full annual source extraction and remaining all-family/Context/Location execution are unfinished, so under-three-hour end-to-end feasibility remains unestablished.

C++ source/quote/native kernels, NumPy reductions, exact structural storage, independently verified quote replay, profile-extrema hoisting and cohort interval indexing are accepted for their measured scopes. V14 now supports the registered17-worker source throughput holdout under existing family limits. Do not rerun unchanged broad checks or treat the holdout as full empirical family completion.
'''+s[b:];s=s.replace('- [Latest focused benchmark16execution]', '- [Historical focused benchmark16execution]').replace('- [Latest focused benchmark 16 execution]', '- [Historical focused benchmark 16 execution]');s=s.replace('## Exact evidence to reuse\n','## Exact evidence to reuse\n\n- [Latest accepted source/replay/fusion and downstream performance](/workspace/trading-research/reports/auction-flow-performance23-review.md).\n');p.write_text(s)
p=coord/'HANDOFF.md';s=p.read_text();a=s.index('Current auction runner:');b=s.index('\n## Drafts that',a);s=s[:a]+'''Current auction runner: `/workspace/trading-research/tools/run_auction_flow_study.py` supports `check`, `profile`, `compute`, `benchmark`, `downstream`, and `throughput`. Active extensionV14 binds accepted23source calibration, exact quote replay and17independent held-out UTC source days. HardwareV2 admits17children under the actual allocation; existing CPU/attempt/output budgets stay unchanged. These remain bounded verification/cost workloads, not a full annual extraction implementation.

Benchmark23passed121tests, all9source comparisons and3continuation replays. Downstream20passed70tests and reproduced18complete anchor/cohort payloads in130.973elapsed seconds using accepted source/trade artifacts. [Exact current performance](/workspace/trading-research/reports/auction-flow-performance23-review.md). The source allowance is152,641.745CPU seconds /261.16GB; a separately frozen quote dual-count recalibration134,722.304CPU seconds awaits the17-window holdout. Full under-three-hour end-to-end feasibility is not established.

No Cursor worker is currently active. Quote replay run20260908T144921Z-8398c571 and fusion run20260908T150342Z-ab015305 completed; exact owned files plus documented Codex corrections were integrated and accepted by23. Failed21 and deliberately stopped22 remain charged. Check CURRENT/coordination state for the active registered throughput run and reuse accepted unchanged evidence.
'''+s[b:];s=s.replace('V5 is not the active source-check extension; V10 is.','V5 is not the active source-check extension; V14 is.');p.write_text(s)
p=coord/'state.json';d=json.loads(p.read_text());current=json.loads((plan/'state/CURRENT.json').read_text());d.update(updated_at=now,status='registered_source_throughput_running_after_accepted23',active_workers=[],active_run=None,latest_verified_source_attempt=current['latest_auction_source_benchmark'],auction_budget=current['auction_budget'],current_assignment='17-file full-UTC-day throughput holdout; accepted source23, downstream20; full end-to-end3hour target not established.');d['latest_verified_downstream_attempt']=current['latest_auction_downstream_check'];p.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n')
p=plan/'state/DEPENDENCIES.json';d=json.loads(p.read_text());d['updated_at']=now;d['accepted_source_dependency_hashes']=w['configuration']['verified_component']['dependencies'];d['actual_source_value_comparison']=w['actual_source_preflight']['complete_retained_source_value_comparison'];d['current_extension_scientific_supplements']=json.loads((r/'validation/AUCTION_FLOW_SOURCE_CHECK_EXTENSION_V14.json').read_text())['scientific_supplements'];extra=[r/'validation/AUCTION_FLOW_SOURCE_CHECK_EXTENSION_V14.json',r/'validation/AUCTION_FLOW_HARDWARE_EXECUTION_V2.json',report,coord/'performance-quote-replay21-integration.json',coord/'performance-quote-fusion21-integration.json'];keys={row['path']:row for row in d['key_files']}
for q in extra:keys[str(q)]=ref(q)
d['key_files']=list(keys.values());d['latest_source_worker']=ref(Path(w['configuration']['check_extension']['path']).parent.parent/'reports/auction-flow-runs'/w['attempt_id']/'worker.json');d['latest_downstream_worker']=current['latest_auction_downstream_check']['worker'];p.write_text(json.dumps(d,indent=2,sort_keys=True)+'\n')
print('Updated report, START_HERE, STATUS, HANDOFF, CURRENT-linked coordination state and dependencies through accepted23.')
