"""Independent observed-minute OHLC examples, not market admission evidence.

JO01–JO17 were specified before the candidate module. Expected price/time
values below are literal arithmetic, never generated by the tested algorithms.
"""
from datetime import date, datetime, timezone
from fractions import Fraction
from pathlib import Path
import json
import unittest

from trading_research.errors import ContractError, DependencyUnavailable, IntegrityError
from trading_research.foundations.cash_calendar import CashCalendar
from trading_research.foundations.contracts import Capability, Target
from trading_research.foundations.units import Ticks, Unit
from trading_research.research.label_ledger import (
    CandidateRecord, LabelDefinition, LabelLedger, ObservationEvidence, SamplingFrame,
)
from trading_research.research.label_payloads import append_price_outcome
from trading_research.research.labels import PathPoint
from trading_research.research.ohlc_ranges import MinuteBars, level_outcome, range_path, wall_interval

M = 60_000_000_000
RAW = "NQM4"


def columns(rows):
    """Rows are (minute_index, OHLC[, known_at_ns, raw_contract, valid])."""
    result = {key: [] for key in (
        "start_ns", "end_ns", "known_at_ns", "open_ticks", "high_ticks",
        "low_ticks", "close_ticks", "volume", "contract_key", "valid")}
    for row in rows:
        minute, prices = row[:2]
        start, end = minute * M, (minute + 1) * M
        values = (start, end, row[2] if len(row) > 2 else end, *prices,
                  10, row[3] if len(row) > 3 else RAW, row[4] if len(row) > 4 else True)
        for key, value in zip(result, values, strict=True):
            result[key].append(value)
    return result


def series(rows):
    return MinuteBars(columns(rows), source_version="independent-observed-minute-fixture-v1")


def full_window(prices):
    return series(tuple((i, price) for i, price in enumerate(prices))).window(0, len(prices) * M,
                                                                            contract_key=RAW)


def utc(ns):
    return datetime.fromtimestamp(ns // 1_000_000_000, timezone.utc).isoformat()


def recipe(start, end, *, start_offset=0, end_offset=0):
    return {"start": {"day_offset": start_offset, "time": start},
            "end": {"day_offset": end_offset, "time": end}, "interval": "[start,end)"}


class OhlcRangeTests(unittest.TestCase):
    def test_jo01_half_open_and_delayed_final_publication(self):
        s = series(((0, (100, 104, 98, 102)),
                    (1, (102, 110, 101, 108), 122_000_000_000),
                    (2, (108, 999, 1, 500))))
        unavailable = s.window(0, 2 * M, contract_key=RAW, available_at=120_000_000_000)
        self.assertFalse(unavailable.complete)
        self.assertIn("final_bar_not_available", unavailable.reasons)
        with self.assertRaises(DependencyUnavailable):
            unavailable.geometry()
        window = s.window(0, 2 * M, contract_key=RAW, available_at=122_000_000_000)
        summary = window.summary()
        self.assertTrue(window.complete)
        self.assertEqual(window.count, 2)
        self.assertEqual(tuple(summary[k] for k in ("open_ticks", "high_ticks", "low_ticks", "close_ticks")),
                         (100, 110, 98, 108))
        self.assertEqual((summary["width_ticks"], summary["available_at_ns"]), (12, 122_000_000_000))
        prefix = series(((0, (100, 104, 98, 102)),
                         (1, (102, 110, 101, 108), 122_000_000_000)))
        self.assertEqual(summary, prefix.window(0, 2 * M, contract_key=RAW,
                                               available_at=122_000_000_000).summary())

    def test_jo02_jo17_units_and_partial_bar_rejection(self):
        bad = columns(((0, (100, 104, 98, 102)),))
        bad["start_ns"] = [1_717_408_800_000]
        bad["end_ns"] = [1_717_408_860_000]
        bad["known_at_ns"] = [1_717_408_860_000]
        with self.assertRaises(ContractError):
            MinuteBars(bad, source_version="milliseconds-misdeclared-as-nanoseconds")
        two_minute = columns(((2, (100, 120, 80, 110)),))
        two_minute["end_ns"] = [240_000_000_000]
        two_minute["known_at_ns"] = [240_000_000_000]
        with self.assertRaises(ContractError):
            MinuteBars(two_minute, source_version="unsupported-two-minute-bar")
        s = series(((0, (100, 101, 99, 100)),))
        with self.assertRaises(ContractError):
            s.window(1, M)

    def test_jo03_missing_first_middle_last_and_invalid_minutes(self):
        expected = (([1, 2], "missing_first_minute"),
                    ([0, 2], "missing_interior_minutes"),
                    ([0, 1], "missing_last_minute"))
        for indices, reason in expected:
            with self.subTest(reason=reason):
                s = series(tuple((i, (100, 101, 99, 100)) for i in indices))
                window = s.window(0, 3 * M, contract_key=RAW)
                self.assertFalse(window.complete)
                self.assertIn(reason, window.reasons)
                self.assertEqual(window.summary()["status"], "unavailable")
                with self.assertRaises(DependencyUnavailable):
                    window.geometry()
                self.assertEqual(range_path(window, low=96, high=104)["status"], "censored")
                self.assertEqual(level_outcome(window, level=Fraction(100), side=1)["status"], "censored")
        invalid = series(((0, (100, 101, 99, 100)), (1, (100, 101, 99, 100), 2 * M, RAW, False)))
        self.assertIn("invalid_source_minutes", invalid.window(0, 2 * M).reasons)
        self.assertIn("missing_all_minutes", invalid.window(3 * M, 4 * M).reasons)
        import pyarrow as pa
        nullable = columns(((0, (100, 101, 99, 100)),
                            (1, (None, None, None, None), 2 * M, None, False),
                            (2, (102, 103, 101, 102))))
        nullable["volume"][1] = None
        table = pa.table(nullable)
        retained = MinuteBars.from_table(table, source_version="nullable-invalid-minute")
        unavailable = retained.window(0, 3 * M)
        self.assertEqual(unavailable.count, 3)
        self.assertIn("invalid_source_minutes", unavailable.reasons)
        with self.assertRaises(DependencyUnavailable):
            unavailable.geometry()
        self.assertEqual(level_outcome(unavailable, level=Fraction(100), side=1)["status"], "censored")
        self.assertEqual(table["open_ticks"].to_pylist(), [100, None, 102])
        self.assertEqual(retained.window(2 * M, 3 * M).geometry().low, 101)
        nullable["valid"][1] = True
        with self.assertRaises(ContractError):
            MinuteBars.from_table(pa.table(nullable), source_version="valid-null-is-forbidden")
        nullable["valid"][1] = False
        nullable["start_ns"][1] += 1
        nullable["end_ns"][1] += 1
        nullable["known_at_ns"][1] += 1
        offgrid = MinuteBars.from_table(pa.table(nullable), source_version="retained-offgrid-invalid-minute")
        self.assertEqual(offgrid.window(0, 3 * M).count, 3)
        self.assertIn("invalid_source_minutes", offgrid.window(0, 3 * M).reasons)
        self.assertTrue(offgrid.window(2 * M, 3 * M).complete)

    def test_jo04_jo05_duplicate_and_cross_raw_contract_rejection(self):
        for duplicate in ((100, 105, 99, 102), (100, 106, 99, 102)):
            with self.subTest(duplicate=duplicate), self.assertRaises(ContractError):
                series(((0, (100, 105, 99, 102)), (0, duplicate)))
        with self.assertRaises(ContractError):
            series(((0, (100, 105, 99, 102)), (0, (202, 208, 200, 205), M, "NQU4")))
        s = series(((0, (100, 105, 99, 102)),
                    (1, (202, 208, 200, 205), 2 * M, "NQU4")))
        joined = s.window(0, 2 * M)
        self.assertIn("raw_contract_transition", joined.reasons)
        with self.assertRaises(DependencyUnavailable):
            joined.geometry()
        self.assertTrue(s.window(0, M, contract_key=RAW).complete)
        self.assertTrue(s.window(M, 2 * M, contract_key="NQU4").complete)
        self.assertIn("different_raw_contract", s.window(M, 2 * M, contract_key=RAW).reasons)

    def test_jo06_jo07_zero_width_and_distinct_exact_geometry(self):
        flat = full_window(((100, 100, 100, 100),))
        summary, geometry = flat.summary(), flat.geometry()
        self.assertEqual(summary["width_ticks"], 0)
        self.assertTrue(summary["zero_width"])
        self.assertIsNone(summary["open_position"])
        self.assertIsNone(geometry.coordinate(Fraction(1, 4)))
        self.assertIsNone(geometry.extension("upper", Fraction(1)))
        self.assertEqual(flat.summary()["status"], "complete")
        with self.assertRaises(ContractError):
            range_path(flat, low=100, high=100)
        g = full_window(((110, 140, 100, 130),)).geometry()
        self.assertEqual((g.width, g.coordinate(Fraction(1, 4)), g.coordinate(Fraction(1, 2)),
                          g.coordinate(Fraction(3, 4)), g.body25(), g.session_body_lower25()),
                         (40, 110, 120, 130, 125, 115))
        self.assertEqual(g.extension("upper", Fraction(133, 100)), Fraction(966, 5))
        self.assertEqual(g.coordinate(Fraction(133, 100)), Fraction(766, 5))
        self.assertEqual(g.extension("lower", Fraction(133, 100)), Fraction(234, 5))

    def test_jo08_strict_break_and_inclusive_reach_are_different(self):
        w = full_window(((100, 104, 96, 100),))
        strict = range_path(w, low=96, high=104, strict=True)
        inclusive = range_path(w, low=96, high=104, strict=False)
        self.assertEqual((strict["path"], strict["upper_reached"], strict["lower_reached"]),
                         ("no_break", False, False))
        self.assertEqual((inclusive["path"], inclusive["upper_reached"], inclusive["lower_reached"]),
                         ("ambiguous", True, True))
        for edge in (96, 104):
            self.assertEqual(level_outcome(w, level=Fraction(edge), side=1)["status"], "definite_level_print")

    def test_jo09_jo10_dual_hit_order_and_open_evidence(self):
        w = series(((0, (100, 106, 94, 102), 61_000_000_000),)).window(0, M)
        result = range_path(w, low=96, high=104)
        self.assertEqual((result["status"], result["path"], result["first_side"]),
                         ("ambiguous", "ambiguous", "ambiguous"))
        self.assertEqual((result["first_interval_start_ns"], result["first_interval_end_ns"],
                          result["second_interval_start_ns"], result["second_interval_end_ns"]), (0, M, 0, M))
        self.assertEqual(result["maturity_at_ns"], 61_000_000_000)
        for opening, expected in ((105, "high_then_low"), (95, "low_then_high"), (104, "ambiguous")):
            with self.subTest(opening=opening):
                r = range_path(full_window(((opening, 106, 94, 100),)), low=96, high=104)
                self.assertEqual(r["path"], expected)
                self.assertFalse(r["origin_open_is_prediction_feature"])
        inclusive = range_path(full_window(((104, 106, 94, 100),)), low=96, high=104, strict=False)
        self.assertEqual(inclusive["first_side"], "upper")

    def test_jo11_later_second_hit_retains_distinct_intervals(self):
        result = range_path(full_window(((100, 103, 94, 99), (99, 106, 98, 105))), low=96, high=104)
        self.assertEqual(result["path"], "low_then_high")
        self.assertEqual((result["first_interval_start_ns"], result["first_interval_end_ns"],
                          result["second_interval_start_ns"], result["second_interval_end_ns"]),
                         (0, M, M, 2 * M))
        self.assertNotIn("first_at_ns", result)
        self.assertNotIn("second_at_ns", result)

    def test_jo12_close_confirmed_reclaim_uses_delayed_publication(self):
        s = series(((0, (100, 108, 99, 106), 61_000_000_000),
                    (1, (106, 107, 101, 102), 123_000_000_000)))
        prefix = range_path(s.window(0, M), low=96, high=104)
        self.assertIsNone(prefix["close_confirmed_reclaim_at_ns"])
        result = range_path(s.window(0, 2 * M), low=96, high=104)
        self.assertEqual(result["first_side"], "upper")
        self.assertEqual(result["close_confirmed_reclaim_at_ns"], 120_000_000_000)
        self.assertEqual(result["reclaim_known_at_ns"], 123_000_000_000)
        at_edge = range_path(full_window(((100, 108, 99, 104),)), low=96, high=104)
        self.assertIsNone(at_edge["close_confirmed_reclaim_at_ns"])

    def test_jo13_contact_bar_excursions_are_bounds_with_side_mirror(self):
        first = full_window(((98, 110, 90, 100),))
        later = full_window(((98, 110, 90, 100), (100, 106, 99, 104)))
        names = ("favorable_lower_ticks", "favorable_upper_ticks", "adverse_lower_ticks", "adverse_upper_ticks")
        one = level_outcome(first, level=Fraction(100), side=1)
        long = level_outcome(later, level=Fraction(100), side=1)
        short = level_outcome(later, level=Fraction(100), side=-1)
        self.assertEqual(tuple(one[n] for n in names), (0, 10, 0, 10))
        self.assertEqual(tuple(long[n] for n in names), (6, 10, 1, 10))
        self.assertEqual(tuple(short[n] for n in names), (1, 10, 6, 10))
        self.assertEqual((long["status"], long["conditional_on_contact"], long["terminal_from_level_ticks"]),
                         ("definite_level_print", False, 4))
        self.assertEqual(short["terminal_from_level_ticks"], -4)
        self.assertEqual((long["contact_interval_start_ns"], long["contact_interval_end_ns"]), (0, M))

    def test_jo14_gap_through_is_not_an_observed_level_print(self):
        w = full_window(((95, 96, 94, 95), (105, 108, 104, 106)))
        result = level_outcome(w, level=Fraction(100), side=1)
        self.assertEqual((result["status"], result["gap_through"]), ("gap_through_without_observed_contact", True))
        no_contact = level_outcome(full_window(((95, 96, 94, 95),)), level=Fraction(100), side=1)
        self.assertEqual(no_contact["status"], "no_contact")
        compatible = level_outcome(full_window(((98, 102, 97, 101),)), level=Fraction(100), side=1)
        self.assertEqual((compatible["status"], compatible["conditional_on_contact"]), ("compatible_straddle_only", True))

    def test_jo15_actual_label_ledger_distinguishes_empty_flat_and_carry(self):
        caps = frozenset({Capability.TERMINAL_RETURN, Capability.EXCURSIONS, Capability.FIRST_PASSAGE})
        variants = (("actual_ohlc_price_observations", (), (), "censored", None),
                    ("actual_ohlc_price_observations", ((M, 100, M + 1),), (), "complete", 0),
                    ("certified_last_observed_mark", (), (), "complete", 0),
                    ("certified_last_observed_mark", (), ((0, M),), "censored", None))
        for process, values, gaps, expected_state, terminal in variants:
            with self.subTest(process=process, values=values, gaps=gaps):
                definition = LabelDefinition("actual-price-definition", "price_path", 0, M, process,
                    favorable_distance=Fraction(3), adverse_distance=Fraction(2), endpoint_group="minute")
                ledger = LabelLedger()
                ledger.add_definition(definition)
                ledger.add_candidate(CandidateRecord("candidate", "birth", "decision-set", "object",
                    "2024-06-03", "episode", SamplingFrame.CLOCK, 0, 0, "untraded",
                    endpoint_group="minute", definition_id=definition.id))
                target = Target("actual-price-target", definition.id, RAW, 0, M, process,
                                "clock", Unit.TICKS, caps)
                points = tuple(PathPoint(at, i, Ticks(price), known)
                               for i, (at, price, known) in enumerate(values))
                outcome = append_price_outcome(ledger, "candidate", definition.id, target=target,
                    initial=Ticks(100), points=points,
                    coverage=ObservationEvidence(M, M + 1, "actual-observation-v1", gaps=gaps),
                    up_ticks=3, down_ticks=2, outcome_id="outcome")
                payload = json.loads(outcome.payload)
                self.assertEqual(outcome.state, expected_state)
                self.assertEqual(payload["data"]["terminal_ticks"], terminal)
                self.assertEqual(payload["data"]["maximum_up_ticks"], terminal)
                self.assertEqual(payload["data"]["maximum_down_ticks"], terminal)
                self.assertEqual(payload["data"]["first_barrier"], "neither" if terminal == 0 else None)
                checkpoint = ledger.checkpoint()
                self.assertEqual(LabelLedger.restore(checkpoint).checkpoint(), checkpoint)
                incompatible = Target("wrong-observation-process", definition.id, RAW, 0, M,
                                      "different_process", "clock", Unit.TICKS, caps)
                with self.assertRaises(ContractError):
                    append_price_outcome(ledger, "candidate", definition.id, target=incompatible,
                        initial=Ticks(100), points=points,
                        coverage=ObservationEvidence(M, M + 1, "actual-observation-v1", gaps=gaps),
                        up_ticks=3, down_ticks=2, outcome_id="wrong-process", supersedes="outcome")
                self.assertEqual(ledger.checkpoint(), checkpoint)

    def test_jo16_dst_short_cash_day_and_overnight_offsets(self):
        expected = ((date(2024, 3, 8), ("2024-03-08T11:00:00+00:00", "2024-03-08T14:00:00+00:00")),
                    (date(2024, 3, 11), ("2024-03-11T10:00:00+00:00", "2024-03-11T13:00:00+00:00")))
        for day, pair in expected:
            self.assertEqual(tuple(map(utc, wall_interval(day, recipe("06:00", "09:00"), "America/New_York"))), pair)
        overnight = wall_interval(date(2024, 6, 3), recipe("20:00", "02:00", start_offset=-1), "America/New_York")
        self.assertEqual(tuple(map(utc, overnight)), ("2024-06-03T00:00:00+00:00", "2024-06-03T06:00:00+00:00"))
        fixed = wall_interval(date(2024, 3, 11), recipe("06:00", "09:00"), "Etc/GMT+5")
        self.assertEqual(tuple(map(utc, fixed)), ("2024-03-11T11:00:00+00:00", "2024-03-11T14:00:00+00:00"))
        for day, start, end in ((date(2024, 3, 10), "02:30", "03:30"),
                                (date(2024, 11, 3), "01:30", "02:30")):
            with self.subTest(day=day), self.assertRaises(ContractError):
                wall_interval(day, recipe(start, end), "America/New_York")
        calendar = CashCalendar(Path(__file__).resolve().parents[1] / "configs/cash-rth-calendar.json")
        day = date(2024, 11, 29)
        cut, _ = wall_interval(day, recipe("00:00", "00:01"), "America/New_York")
        cash = calendar.resolve(day, cut=cut)
        self.assertEqual(cash.state, "early_close")
        self.assertEqual((utc(cash.open_at), utc(cash.close_at)),
                         ("2024-11-29T14:30:00+00:00", "2024-11-29T18:00:00+00:00"))
        self.assertEqual(cash.scope, "cash_equity_rth_context")
        self.assertEqual(wall_interval(day, recipe("09:30", "13:00"), "America/New_York"),
                         (cash.open_at, cash.close_at))

    def test_exact_numerical_identity_rejects_bool_and_mutable_source_claims(self):
        for key in ("open_ticks", "high_ticks", "low_ticks", "close_ticks", "volume"):
            values = columns(((0, (1, 2, 0, 1)),))
            values[key] = [True]
            with self.subTest(field=key), self.assertRaises(ContractError):
                MinuteBars(values, source_version="typed-numerical-domain")
        with self.assertRaises(ContractError):
            MinuteBars(columns(((0, (100, 101, 99, 100)),)), source_version={"mutable": "claim"})
        with self.assertRaises(ContractError):
            series(((0, (100, 101, 99, 100)),)).window(0, M, available_at=True)

    def test_later_definite_print_does_not_disappear_after_earlier_straddle(self):
        # The110 high can precede every actual100 print. The first definite
        # equality is the second bar's close, so it cannot raise a lower bound.
        result = level_outcome(full_window(((98, 110, 97, 101), (103, 104, 99, 100))),
                               level=Fraction(100), side=1)
        self.assertEqual((result["status"], result["conditional_on_contact"]), ("definite_level_print", False))
        self.assertEqual((result["contact_interval_start_ns"], result["contact_interval_end_ns"]), (0, M))
        self.assertEqual((result["first_definite_interval_start_ns"], result["first_definite_interval_end_ns"]),
                         (M, 2 * M))
        self.assertEqual((result["first_actual_contact_lower_ns"], result["first_actual_contact_upper_ns"]),
                         (0, 2 * M))
        self.assertEqual((result["favorable_lower_ticks"], result["favorable_upper_ticks"],
                          result["adverse_lower_ticks"], result["adverse_upper_ticks"]), (0, 10, 0, 3))
        later = level_outcome(full_window(((98, 110, 97, 101), (103, 104, 99, 100),
                                           (100, 106, 99, 104))), level=Fraction(100), side=1)
        self.assertEqual((later["favorable_lower_ticks"], later["favorable_upper_ticks"],
                          later["adverse_lower_ticks"], later["adverse_upper_ticks"]), (6, 10, 1, 3))
        possible_only = level_outcome(full_window(((98, 110, 97, 101), (103, 105, 99, 102))),
                                      level=Fraction(100), side=1)
        self.assertEqual((possible_only["status"], possible_only["conditional_on_contact"]),
                         ("compatible_straddle_only", True))
        self.assertEqual((possible_only["favorable_lower_ticks"], possible_only["favorable_upper_ticks"]),
                         (2, 10))

    def test_admitted_window_cannot_change_under_the_same_identity(self):
        original_columns = columns(((0, (100, 105, 99, 102)),))
        copied = MinuteBars(original_columns, source_version="immutable-fixture")
        original_columns["high_ticks"][0] = 999
        self.assertEqual(copied.window(0, M).geometry().high, 105)
        cached = copied.window(0, M, available_at=M)
        first_summary = cached.summary()
        original_version = first_summary["window_version"]
        first_summary["high_ticks"] = 999
        first_summary["exclusion_reasons"].append("caller_annotation")
        self.assertEqual(cached.summary()["high_ticks"], 105)
        self.assertEqual(cached.summary()["exclusion_reasons"], [])
        self.assertEqual(cached.summary()["window_version"], original_version)
        self.assertEqual(cached.geometry().high, 105)
        unavailable = copied.window(0, M, available_at=M - 1)
        self.assertNotEqual(unavailable.version, original_version)
        changed = unavailable.summary()
        changed["exclusion_reasons"].clear()
        self.assertIn("final_bar_not_available", unavailable.summary()["exclusion_reasons"])
        with self.assertRaises(DependencyUnavailable):
            unavailable.geometry()
        with self.assertRaises((AttributeError, TypeError, ContractError)):
            copied.source_version = "changed-source-claim"
        for field, replacement in (("high", 999), ("known", 10 * M)):
            s = series(((0, (100, 105, 99, 102)),))
            window = s.window(0, M, available_at=M)
            original_version = window.version
            try:
                getattr(s, field)[0] = replacement
            except (TypeError, AttributeError, ContractError):
                self.assertEqual(window.version, original_version)
                self.assertEqual(window.summary()["high_ticks"], 105)
                self.assertEqual(window.summary()["available_at_ns"], M)
            else:
                with self.assertRaises(IntegrityError):
                    window.summary()

    def test_negative_fraction_contact_and_strict_gap_keep_exact_comparison_semantics(self):
        result = level_outcome(full_window(((-1, 0, -3, -2), (1, 2, 0, 1))),
                               level=Fraction(-3, 2), side=1)
        self.assertEqual(result["status"], "compatible_straddle_only")
        self.assertEqual((result["level_numerator"], result["level_denominator"]), (-3, 2))
        self.assertTrue(result["gap_through"])
        self.assertIsNone(result["first_definite_interval_start_ns"])
        self.assertEqual((result["favorable_lower_ticks"], result["favorable_upper_ticks"],
                          result["adverse_lower_ticks"], result["adverse_upper_ticks"]),
                         (3.5, 3.5, 0.5, 1.5))
        self.assertEqual(result["terminal_from_level_ticks"], 2.5)
